apiVersion: batch/v1
kind: Job
metadata:
  name: setup
spec:
  template:
    metadata:
      name: setup
    spec:
      containers:
      - name: setup
        image: rotati/todoapi:90d92cd
        command: ["/bin/bash", "./setup.production.sh"]
        # command: ["bin/rake", "db:migrate", "RAILS_ENV=production"]
        env:
        - name: PASSENGER_APP_ENV
          value: production
      restartPolicy: Never