apiVersion: batch/v1
kind: Job
metadata:
  name: setup
  namespace: staging
spec:
  template:
    metadata:
      name: setup
    spec:
      containers:
      - name: setup
        image: rotati/todoapi:LAST_COMMIT
        command: ["/bin/bash", "./setup.staging.sh"]
        env:
        - name: PASSENGER_APP_ENV
          value: staging
      restartPolicy: Never