apiVersion: v1
kind: Service
metadata:
  name: todoapi
  labels:
    app: todoapi
spec:
  ports:
    - port: 80
  selector:
    app: todoapi
    tier: backend
  type: LoadBalancer
---
apiVersion: extensions/v1beta1 #TODO update version
kind: Deployment
metadata:
  name: todoapi
  labels:
    app: todoapi
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: todoapi
        tier: backend
    spec:
      containers:
      - image: rotati/todoapi:90d92cd
        name: todoapi
        env:
        - name: PASSENGER_APP_ENV
          value: production
        ports:
        - containerPort: 80
          name: todoapi
        imagePullPolicy: Always
