version: '2'
services:
  todoapi_setup:
    build: .
    depends_on:
      - postgres
    environment:
      - PASSENGER_APP_ENV=development
    entrypoint: ./setup.sh
  todoapi:
    container_name: todoapi
    build: .
    depends_on:
      - postgres
      - todoapi_setup
    environment:
      - PASSENGER_APP_ENV=development
    ports:
      - "80:80"
    volumes:
      - .:/home/app/todoapi
  postgres:
    image: postgres:9.6.6
    container_name: tododb
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=todoapi
      - POSTGRES_DB=todoapi_development
    volumes_from:
      - postgres_data
  postgres_data:
      image: postgres:9.6.6
      volumes:
        - /var/lib/postgresql/data
      command: /bin/true